unstable_features=true

brace_style="PreferSameLine"
control_brace_style="AlwaysSameLine"
fn_args_layout="Compressed"
indent_style="Block"

trailing_comma="Never"
overflow_delimited_expr=true

wrap_comments=true
format_code_in_doc_comments=true
normalize_doc_attributes=true

condense_wildcard_suffixes=true

format_strings=true
hex_literal_case="Lower"

imports_granularity="Module"
group_imports="StdExternalCrate"

reorder_impl_items=true
where_single_line=true

use_field_init_shorthand=true
use_try_shorthand=true

use_small_heuristics="Max"
