//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "filters")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    pub name: Option<String>,
    pub enabled: i8,
    pub server: i64,
    pub creator: Option<i64>,
    pub r#type: String,
    pub type_settings: Option<String>,
    pub server_scope: i8,
    pub server_scope_settings: Option<String>,
    pub user_scope: i8,
    pub user_scope_settings: Option<String>,
    pub effect: String
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
